### ISSUE TITLE
loadSkeleton on clBody in sample app cause layout to lose its constraints

### ISSUE THREAD

**Issue by moodi1999** [ericktijerou/koleton#4]
in JourneyDetailFragment, i add loadSkeleton  to clBody and it gets call after clHeader skeleton is done.
body constraints are OK when skeleton loaded, but when it gets hide, it loses its constrains and goes on top.
i couldn't realize what's the problem, so it will be great if you could explain what happened there?

**Comment by ericktijerou** [comment]
Hi @moodi1999 👋,

Thank you for your bug report. It is appreciated.

When the skeleton is showing, the view has set new `layoutParams` (**FrameLayout.LayoutParams**) because it is contained within a **ShimmerFrameLayout** and this layout has the original `layoutParams` (**ConstraintLayout.LayoutParams**).

When `hideSkeleton` is called the view hierarchy is restored and the `layoutParams` of the view return to its original configuration.

I'll check this process in the case you described.

Have a nice day!

**Comment by ericktijerou** [comment]
@moodi1999 I've reproduced the issue and fixed it. Please try out `0.7.3` version.

Thanks a lot for your contribution.
